Client Only
    https://modrinth.com/mod/cloth-config
    https://modrinth.com/mod/fabric-api
    https://www.curseforge.com/minecraft/mc-mods/fabric-api
    https://modrinth.com/mod/modmenu
    https://modrinth.com/mod/fabric-language-kotlin
    https://modrinth.com/mod/chat-heads
    https://modrinth.com/mod/lithium
    https://modrinth.com/mod/ferrite-core
    https://modrinth.com/mod/notenoughcrashes
    https://modrinth.com/mod/mixin-conflict-helper
    https://modrinth.com/mod/no-chat-reports
    https://modrinth.com/mod/simple-voice-chat
    https://modrinth.com/mod/sound-physics-remastered
    https://modrinth.com/mod/voice-chat-interaction
    https://modrinth.com/mod/deathlog
    https://modrinth.com/mod/enchantment-lore 
    https://modrinth.com/mod/lambdynamiclights
    https://modrinth.com/mod/sodium
    https://modrinth.com/mod/starlight
    https://modrinth.com/mod/iris
    https://modrinth.com/mod/borderless-mining
    https://modrinth.com/mod/better-ping-display
    https://www.curseforge.com/minecraft/mc-mods/controlling
    https://modrinth.com/mod/essential
    https://modrinth.com/mod/indium
    https://modrinth.com/mod/lazydfu
    https://modrinth.com/mod/memory-usage-screen
    https://modrinth.com/mod/nobar
    https://modrinth.com/mod/perspective-mod-redux
    https://modrinth.com/mod/shulkerboxtooltip
    https://modrinth.com/mod/sodium-extra
    https://modrinth.com/mod/reeses-sodium-options
    https://modrinth.com/mod/fastload
    https://modrinth.com/mod/krypton
Content/Actual changes (Requires client-side afaik)
        Resource Packs
            https://modrinth.com/resourcepack/eclectic-trove-legendary-tooltips
            https://www.curseforge.com/minecraft/texture-packs/stoneborn-dwarven-fantasy-inspired-ui-overhaul
        Libs
            https://modrinth.com/mod/forge-config-api-port
            https://www.curseforge.com/minecraft/mc-mods/bookshelf
            https://modrinth.com/mod/transparent
            https://modrinth.com/mod/cardinal-components-api
            https://modrinth.com/mod/data-attributes
            https://modrinth.com/mod/badpackets
            https://modrinth.com/mod/iceberg
            https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric
            https://modrinth.com/mod/bclib       
            https://modrinth.com/mod/trinkets
            https://www.curseforge.com/minecraft/mc-mods/malilib
            https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric
            https://modrinth.com/mod/geckolib
            https://modrinth.com/mod/dawn
            https://modrinth.com/mod/prism-lib 
            https://modrinth.com/mod/brrp/
        Player Interactions
            https://modrinth.com/mod/presence-footsteps
            https://modrinth.com/mod/crawl
            https://modrinth.com/mod/simple-voice-chat
            https://modrinth.com/mod/sound-physics-remastered
            https://modrinth.com/mod/voice-chat-interaction
            https://modrinth.com/mod/presence-footsteps
            https://www.curseforge.com/minecraft/mc-mods/friendly-fire
            https://modrinth.com/mod/arcanus
            https://modrinth.com/mod/playerex
        Informational
            https://modrinth.com/mod/emi
            https://www.curseforge.com/minecraft/mc-mods/litematica
            https://modrinth.com/mod/journeymap
            https://modrinth.com/mod/appleskin
            https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge
            https://modrinth.com/mod/equipment-compare
            https://modrinth.com/mod/wthit
            https://modrinth.com/mod/entityculling
        Items/misc
            https://www.curseforge.com/minecraft/mc-mods/natures-compass
            https://www.curseforge.com/minecraft/mc-mods/explorers-compass
            https://modrinth.com/mod/charm
            https://modrinth.com/mod/adorn
            https://modrinth.com/mod/extraalchemy
            https://modrinth.com/mod/crusade
            https://modrinth.com/mod/immersive-armors
            https://modrinth.com/mod/travelersbackpack
            https://modrinth.com/mod/voidtotem
            https://modrinth.com/mod/legendary-tooltips
            https://modrinth.com/mod/advancement-plaques
            https://modrinth.com/resourcepack/embellished-stone-advancements-plaques
            https://modrinth.com/mod/fallingtree
            https://modrinth.com/mod/fallingleaves
            https://modrinth.com/mod/visuality
            https://modrinth.com/mod/lambdabettergrass
            https://modrinth.com/mod/continuity
        Mobs
            https://modrinth.com/mod/goblin-traders-fabric
        Progression
            https://www.curseforge.com/minecraft/mc-mods/techreborn
            https://www.curseforge.com/minecraft/mc-mods/ultris-boss-expansion
            https://modrinth.com/mod/advanced-netherite
            https://modrinth.com/mod/create
            https://modrinth.com/mod/hydration
            https://modrinth.com/mod/eldritch-mobs
            https://modrinth.com/mod/friends-and-foes
            https://www.curseforge.com/minecraft/mc-mods/archon
            https://modrinth.com/mod/origins
        Enchantments
            https://www.curseforge.com/minecraft/mc-mods/fabric-enchantments
            https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions
        Structures
            https://www.curseforge.com/minecraft/mc-mods/dungeon-now-loading
            https://modrinth.com/mod/ct-overhaul-village
            https://modrinth.com/mod/additional-structures
            https://modrinth.com/mod/towns-and-towers
            https://modrinth.com/mod/promenade
            https://modrinth.com/mod/the-graveyard-fabric
            https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric
            https://modrinth.com/mod/bosses-of-mass-destruction
            https://modrinth.com/mod/stoneholm
            https://modrinth.com/mod/moogs-voyager-structures/versions
            https://modrinth.com/mod/repurposed-structures-fabric
            https://modrinth.com/mod/immersive-structures
            https://modrinth.com/mod/architects-palette-fabric
        World/Biomes
            https://www.curseforge.com/minecraft/mc-mods/terralith
            https://modrinth.com/mod/betternether
            https://modrinth.com/mod/traverse
            https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric
            https://modrinth.com/mod/betterend
            https://www.curseforge.com/minecraft/mc-mods/ecologics
            https://modrinth.com/mod/fabric-seasons
            https://modrinth.com/mod/sky-villages
            https://www.curseforge.com/minecraft/mc-mods/naturalist
            https://modrinth.com/mod/more-geodes
